#!/bin/sh
#
#SBATCH -A sml

#SBATCH -A sml
#SBATCH -c 4
#SBATCH -t 60:00:00
#SBATCH --gres=gpu:1
#SBATCH --exclude=yolanda,gonzo
#SBATCH -J "cifar"

#eval "$(conda shell.bash hook)"
#conda activate grad

ulimit -n 2048
