#!/bin/sh
#
#SBATCH -A sml

# ONE OR THE OTHER
#--------------------
#SBATCH -c 1
#--------------------
## SBATCH -c
## SBATCH --gres=gpu:1
#--------------------

#SBATCH -w MACHINE
#SBATCH -t 60:00:00

#eval "$(conda shell.bash hook)"
#conda activate grad

